version: '3.6'
services:

  database:
    image: postgres:11
    container_name: database
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./pg_data:${PGDATA:-/var/lib/postgresql/data}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data}
      - POSTGRES_DB=postgres

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    image: django
    container_name: django
    ports:
      - 8000:8000
    volumes:
      - .:/code
      - ./static:/code/static
      - ./media:/code/media
    environment:
      - UWSGI_UID=${UWSGI_UID:-1000}
      - UWSGI_GID=${UWSGI_GID:-1000}

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - .:/code
      - ./static:/code/static
      - ./media:/code/media
      - ${NGINX_DEFAULT_CONF:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERT:-./ssl/ssl_dev.crt}:/etc/ssl/SSL.crt  # SSL development certificate
      - ${NGINX_SSL_KEY:-./ssl/ssl_dev.key}:/etc/ssl/SSL.key   # SSL development key

  neo4j:
    image: rencinrig/neo4j-apoc:latest
    container_name: neo4j
    user: ${NEO4J_UID:-1000}:${NEO4J_GID:-1000}
    ports:
      - 7474:7474  # for HTTP
      - 7473:7473  # for HTTPS
      - 7687:7687  # for Bolt
    volumes:
      - ${NEO4J_DATA_PATH_HOST:-$(pwd)/neo4j/data}:${NEO4J_DATA_PATH_DOCKER:-/data}
      - ${NEO4J_IMPORTS_PATH_HOST:-$(pwd)/neo4j/imports}:${NEO4J_IMPORTS_PATH_DOCKER:-/imports}
      - ${NEO4J_LOGS_PATH_HOST:-$(pwd)/neo4j/logs}:${NEO4J_LOGS_PATH_DOCKER:-/logs}
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASS:-password}

