version: '3.6'
services:

  database:
    image: postgres:11
    container_name: database
    networks:
      - backend
    volumes:
      - ./pg_data/data:${PGDATA:-/var/lib/postgresql/data}:z
      - ./pg_data/logs:${POSTGRES_INITDB_WALDIR:-/var/log/postgresql}:z
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data}
      - POSTGRES_DB=postgres

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    image: django
    container_name: django
    depends_on:
      - database
      - neo4j
      - kafka
    networks:
      - frontend
      - backend
    volumes:
      - .:/code:z
      - ./static:/code/static:z
      - ./media:/code/media:z
    environment:
      - UWSGI_UID=${UWSGI_UID:-1000}
      - UWSGI_GID=${UWSGI_GID:-1000}

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
      - 8443:443
    networks:
      - frontend
    volumes:
      - .:/code:z
      - ./static:/code/static:Z
      - ./media:/code/media:z
      - ${NGINX_DEFAULT_CONF:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf:z
      - ${NGINX_SSL_CERT:-./ssl/ssl_dev.crt}:/etc/ssl/SSL.crt:ro,z  # SSL development certificate
      - ${NGINX_SSL_KEY:-./ssl/ssl_dev.key}:/etc/ssl/SSL.key:ro,z   # SSL development key

  neo4j:
    image: rencinrig/neo4j-apoc:latest
    container_name: neo4j
    user: ${NEO4J_UID:-1000}:${NEO4J_GID:-1000}
    networks:
      - backend
    volumes:
      - ${NEO4J_DATA_PATH_HOST:-$(pwd)/neo4j/data}:${NEO4J_DATA_PATH_DOCKER:-/data}:z
      - ${NEO4J_IMPORTS_PATH_HOST:-$(pwd)/neo4j/imports}:${NEO4J_IMPORTS_PATH_DOCKER:-/imports}:z
      - ${NEO4J_LOGS_PATH_HOST:-$(pwd)/neo4j/logs}:${NEO4J_LOGS_PATH_DOCKER:-/logs}:z
      - ${NGINX_SSL_CERT:-./ssl/ssl_dev.crt}:/ssl/neo4j.cert:ro,z  # SSL development certificate
      - ${NGINX_SSL_KEY:-./ssl/ssl_dev.key}:/ssl/neo4j.key:ro,z    # SSL development key
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASS:-password}

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    networks:
      - backend

  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    container_name: kafka
    depends_on:
      - zookeeper
    networks:
      - backend
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT:-zookeeper:2181}
      - KAFKA_LISTENERS=${KAFKA_LISTENERS:-PLAINTEXT://:9092}
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS:-PLAINTEXT://127.0.0.1:9092}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ${KAFKA_DATA_PATH_HOST:-./kafka}:/kafka:z

networks:
  frontend:
  backend: